apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-backend
  template:
    metadata:
      name: nginx-backend-pod
      labels:
        app: nginx-backend
    spec:
      containers:
        - name: backend
          image: dmella04/test-backend:latest
          imagePullPolicy: Always
          command: ["rails", "s"]
          ports:
            - name: backned-port80
              containerPort: 3000
          volumeMounts:
            - name: log
              mountPath: /app/log
            - name: public
              mountPath: /app/public
        - name: nginx
          image: dmella04/test-nginx:latest
          imagePullPolicy: Always
          ports:
            - name: nginx-port80
              containerPort: 80
          volumeMounts:
            - name: log
              mountPath: /app/log
            - name: public
              mountPath: /app/public
      volumes:
        - name: log
          hostPath:
            path: /app/log
        - name: public
          hostPath:
            path: /app/public
